### ISSUE TITLE
Sometimes the last block timestamp is cut in 2 lines although there is plenty of space

### ISSUE THREAD

**Issue by rex4539** [johanssonlc/zcash-full-node-wallet#4]
Resizing the window does not fix it. Seems to be related to a combination of numbers in the timestamp.

![screen shot 2018-04-11 at 18 50 46](https://user-images.githubusercontent.com/227442/38628191-73753bb4-3db9-11e8-9ba2-0240a6dad659.png)

**Comment by rex4539** [comment]
![screen shot 2018-04-18 at 08 47 43](https://user-images.githubusercontent.com/227442/38913864-97ee856e-42e5-11e8-9903-4f8a0fb2e747.png)

**Comment by johanssonlc** [comment]
Sorry for the late response. Hmm, I don't see that behaviour in my environment. I'm going to see if it is either java 9 och osx related.

**Comment by rex4539** [comment]
This project is dead so retracting.
