### ISSUE TITLE
Pull from upstream

### ISSUE THREAD

**Issue by rex4539** [johanssonlc/zcash-full-node-wallet#7]
Would really appreciate a pull from upstream to bring the client up to date with the latest ZEN.

**Comment by johanssonlc** [comment]
Yes, will do

**Comment by rex4539** [comment]
Zcash GUI bounties from the ZenCash team: https://twitter.com/mineZcash/status/1017966738867179523?s=09

**Comment by rex4539** [comment]
This project is dead so retracting.
